version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: enviafolha-backend
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - PYTHONUNBUFFERED=1
      # Evolution API Configuration
      - EVOLUTION_SERVER_URL=${EVOLUTION_SERVER_URL:-}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME:-}
    volumes:
      # Persistir uploads e arquivos processados
      - ./data/uploads:/app/uploads
      - ./data/enviados:/app/enviados
      - ./data/holerites_formatados_final:/app/holerites_formatados_final
      # Persistir dados dos funcionários
      - ./backend/employees.json:/app/employees.json
      # Arquivo de configuração (se existir)
      - ./.env:/app/.env:ro
    networks:
      - enviafolha-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: enviafolha-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8002/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
    networks:
      - enviafolha-network
    profiles:
      - with-frontend

networks:
  enviafolha-network:
    driver: bridge

volumes:
  uploads_data:
  enviados_data:
  holerites_data:
  postgres_data:
