"""drop_sector_column_from_employees

Revision ID: 400a511daf81
Revises: 6f7c6d04b646
Create Date: 2026-03-27 17:22:40.029373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400a511daf81'
down_revision: Union[str, Sequence[str], None] = '6f7c6d04b646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
