"""add_company_worklocation_and_absolute_id

Revision ID: 6f7c6d04b646
Revises: c11e602e39dc
Create Date: 2026-03-27 15:37:08.482066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f7c6d04b646'
down_revision: Union[str, Sequence[str], None] = 'c11e602e39dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('payroll_prefix', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('work_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_complement', sa.String(length=100), nullable=True),
    sa.Column('address_neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=9), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_locations_code'), 'work_locations', ['code'], unique=False)
    op.create_index(op.f('ix_work_locations_company_id'), 'work_locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_work_locations_id'), 'work_locations', ['id'], unique=False)
    op.execute('DROP TABLE IF EXISTS timecard_periods CASCADE')
    op.execute('DROP TABLE IF EXISTS timecard_processing_logs CASCADE')
    op.execute('DROP TABLE IF EXISTS audit_logs CASCADE')
    op.execute('DROP TABLE IF EXISTS system_settings CASCADE')
    op.execute('DROP TABLE IF EXISTS timecard_data CASCADE')
    op.drop_index('idx_benefit_records_employee_id', table_name='benefit_records')
    op.drop_index('idx_benefit_records_unified_code', table_name='benefit_records')
    op.drop_index('idx_benefits_data_cpf', table_name='benefits_data')
    op.drop_index('idx_benefits_data_period_id', table_name='benefits_data')
    op.add_column('employees', sa.Column('absolute_id', sa.String(length=80), nullable=True))
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('work_location_id', sa.Integer(), nullable=True))
    op.alter_column('employees', 'unique_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_employees_unique_id', table_name='employees')
    op.create_index(op.f('ix_employees_unique_id'), 'employees', ['unique_id'], unique=False)
    op.create_index(op.f('ix_employees_absolute_id'), 'employees', ['absolute_id'], unique=True)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_cpf'), 'employees', ['cpf'], unique=False)
    op.create_index(op.f('ix_employees_work_location_id'), 'employees', ['work_location_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'work_locations', ['work_location_id'], ['id'])
    op.drop_index('idx_hr_snapshots_calculation_date', table_name='hr_indicator_snapshots')
    op.drop_index('idx_hr_snapshots_indicator_type', table_name='hr_indicator_snapshots')
    op.drop_index('idx_leave_records_employee_id', table_name='leave_records')
    op.drop_index('idx_leave_records_unified_code', table_name='leave_records')
    op.drop_index('idx_movement_records_employee_id', table_name='movement_records')
    op.drop_index('idx_movement_records_unified_code', table_name='movement_records')
    op.alter_column('payroll_periods', 'company',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'0060'::character varying"))
    op.drop_index('idx_payroll_records_competence', table_name='payroll_records')
    op.drop_index('idx_payroll_records_employee_id', table_name='payroll_records')
    op.drop_index('idx_payroll_records_unified_code', table_name='payroll_records')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_index('idx_send_queue_items_queue_id', table_name='send_queue_items')
    op.drop_index('idx_send_queue_items_status', table_name='send_queue_items')
    op.drop_index('idx_send_queues_queue_id', table_name='send_queues')
    op.drop_index('idx_send_queues_status', table_name='send_queues')
    op.drop_index('idx_system_logs_category', table_name='system_logs')
    op.drop_index('idx_system_logs_created_at', table_name='system_logs')
    op.drop_index('idx_system_logs_level', table_name='system_logs')
    op.drop_index('idx_system_logs_user_id', table_name='system_logs')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('idx_system_logs_user_id', 'system_logs', ['user_id'], unique=False)
    op.create_index('idx_system_logs_level', 'system_logs', ['level'], unique=False)
    op.create_index('idx_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_system_logs_category', 'system_logs', ['category'], unique=False)
    op.create_index('idx_send_queues_status', 'send_queues', ['status'], unique=False)
    op.create_index('idx_send_queues_queue_id', 'send_queues', ['queue_id'], unique=False)
    op.create_index('idx_send_queue_items_status', 'send_queue_items', ['status'], unique=False)
    op.create_index('idx_send_queue_items_queue_id', 'send_queue_items', ['queue_id'], unique=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index('idx_payroll_records_unified_code', 'payroll_records', ['unified_code'], unique=False)
    op.create_index('idx_payroll_records_employee_id', 'payroll_records', ['employee_id'], unique=False)
    op.create_index('idx_payroll_records_competence', 'payroll_records', ['competence'], unique=False)
    op.alter_column('payroll_periods', 'company',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'0060'::character varying"))
    op.create_index('idx_movement_records_unified_code', 'movement_records', ['unified_code'], unique=False)
    op.create_index('idx_movement_records_employee_id', 'movement_records', ['employee_id'], unique=False)
    op.create_index('idx_leave_records_unified_code', 'leave_records', ['unified_code'], unique=False)
    op.create_index('idx_leave_records_employee_id', 'leave_records', ['employee_id'], unique=False)
    op.create_index('idx_hr_snapshots_indicator_type', 'hr_indicator_snapshots', ['indicator_type'], unique=False)
    op.create_index('idx_hr_snapshots_calculation_date', 'hr_indicator_snapshots', ['calculation_date'], unique=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_work_location_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_cpf'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_absolute_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_unique_id'), table_name='employees')
    op.create_index('ix_employees_unique_id', 'employees', ['unique_id'], unique=True)
    op.alter_column('employees', 'unique_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('employees', 'work_location_id')
    op.drop_column('employees', 'company_id')
    op.drop_column('employees', 'absolute_id')
    op.create_index('idx_benefits_data_period_id', 'benefits_data', ['period_id'], unique=False)
    op.create_index('idx_benefits_data_cpf', 'benefits_data', ['cpf'], unique=False)
    op.create_index('idx_benefit_records_unified_code', 'benefit_records', ['unified_code'], unique=False)
    op.create_index('idx_benefit_records_employee_id', 'benefit_records', ['employee_id'], unique=False)
    op.create_table('timecard_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('normal_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('overtime_50', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('overtime_100', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('night_overtime_50', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('night_overtime_100', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('night_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('absences', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('dsr_debit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('bonus_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('upload_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='timecard_data_employee_id_fkey'),
    sa.ForeignKeyConstraint(['period_id'], ['timecard_periods.id'], name='timecard_data_period_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name='timecard_data_processed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='timecard_data_pkey')
    )
    op.create_index('ix_timecard_data_id', 'timecard_data', ['id'], unique=False)
    op.create_index('ix_timecard_data_employee_number', 'timecard_data', ['employee_number'], unique=False)
    op.create_index('idx_timecard_data_period_id', 'timecard_data', ['period_id'], unique=False)
    op.create_index('idx_timecard_data_employee_number', 'timecard_data', ['employee_number'], unique=False)
    op.create_index('idx_timecard_data_employee_id', 'timecard_data', ['employee_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=True)
    op.create_index('ix_system_settings_id', 'system_settings', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_table('timecard_processing_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processing_summary', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processing_time', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['timecard_periods.id'], name='timecard_processing_logs_period_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name='timecard_processing_logs_processed_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='timecard_processing_logs_pkey')
    )
    op.create_index('ix_timecard_processing_logs_id', 'timecard_processing_logs', ['id'], unique=False)
    op.create_table('timecard_periods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='timecard_periods_pkey')
    )
    op.create_index('ix_timecard_periods_id', 'timecard_periods', ['id'], unique=False)
    op.drop_index(op.f('ix_work_locations_id'), table_name='work_locations')
    op.drop_index(op.f('ix_work_locations_company_id'), table_name='work_locations')
    op.drop_index(op.f('ix_work_locations_code'), table_name='work_locations')
    op.drop_table('work_locations')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
